### ISSUE TITLE
小米上架审核不通过 

### ISSUE THREAD

**Issue by practicingman** [RxReader/link_kit#1]
APP向用户明示SDK的收集使用规则，未经用户同意，SDK存在收集io.github.v7lin,io.flutter.embedding获取安装列表的行为。
这个queryIntentActivitiesAsUser小米不允许😓

```
android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1019)
android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:992)
io.github.v7lin.link_kit.LinkKitPlugin.isFLKIntent(LinkKitPlugin.java:139)
io.github.v7lin.link_kit.LinkKitPlugin.onNewIntent(LinkKitPlugin.java:108)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent(FlutterEngineConnectionRegistry.java:830)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent(FlutterEngineConnectionRegistry.java:446)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent(FlutterActivityAndFragmentDelegate.java:777)
io.flutter.embedding.android.FlutterActivity.onNewIntent(FlutterActivity.java:733)
android.app.Activity.performNewIntent(Activity.java:7082)
android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1309)
android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1321)
android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3267)
android.app.ActivityThread.performNewIntents(ActivityThread.java:3283)
android.app.ActivityThread.handleNewIntent(ActivityThread.java:3299)
android.app.ActivityThread.-wrap14(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1999)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6843)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)	
```

**Comment by droplet-js** [comment]
有没有一种可能 … 你改一下用户协议和隐私政策就能过审 … 我的App就已过审ov华米腾讯360等等 …

**Comment by droplet-js** [comment]
queryIntentActivities 这是一个非常常用的函数 … 在Android中的分享、确定intent是否能打开（launchurl插件）等是一个非常重要的函数

**Comment by droplet-js** [comment]
你在隐私政策/用户协议上加上一条获取安装列表是为了深度链接打开app功能即可

**Comment by droplet-js** [comment]
https://github.com/flutter/plugins/blob/910b61d1bf4cd89fd7c2db59659cfa2047f4859e/packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L414

**Comment by practicingman** [comment]
我隐私政策里面有一条

> （6）Flutter框架
> 使用目的：使用了Flutter框架（io.flutter.embedding）开发，包含了LinkKit（io.github.v7lin），为了用户点击深度链接时可以在APP中打开。
> 收集数据类型：【获取安装列表】。这是为了不响应本该由其他应用响应的Intent，即不影响QQ、微信登陆等功能。该信息不存储、不上传。
> 官网链接：https://flutter.dev/

但是还是不给通过。自动审核的时候就不通过

看人品可能…………

我暂时把作者的代码拷贝到本地，通过intent的datastring判断处不处理了……

**Comment by droplet-js** [comment]
> 我隐私政策里面有一条
> 
> > （6）Flutter框架
> > 使用目的：使用了Flutter框架（io.flutter.embedding）开发，包含了LinkKit（io.github.v7lin），为了用户点击深度链接时可以在APP中打开。
> > 收集数据类型：【获取安装列表】。这是为了不响应本该由其他应用响应的Intent，即不影响QQ、微信登陆等功能。该信息不存储、不上传。
> > 官网链接：https://flutter.dev/
> 
> 但是还是不给通过。自动审核的时候就不通过
> 
> 看人品可能…………
> 
> 我暂时把作者的代码拷贝到本地，通过intent的datastring判断处不处理了……

刚反应过来，getInitialLink 这个函数不能在同意「隐私协议」前调用。小米应用商店的回复也是说，你在同意「隐私协议」前调用了 queryIntentActivitiesAsUser。
